[wokspace]

members = ["rgb-core", "rust-dlc", "bitswap", "payjoin", "aluvm", "baid58"]

[package]
name = "Bitswap_Demo_CLI"
version = "1.0.24-alpha"
edition = "2021"
description = "AMM DEX on RGB Protocol and Lightning Network"
license = "Business Source License 1.1"

[memmbers]

swap = "amm, dlc"
dlc = "message"
amm_contract = "amm contract"
ldk = "invoice, paymenthash, rgb_assets"

[dex.dependencies]
swap = "0.1.0"


[core_functions]
rgb-core = "0.11.0-beta.6" 
dlc = "0.4"
bitswap = "1.0.24"
strict_encoding = "~2.7.0-beta.4"
strict_types = "2.7.0-beta.4"
aluvm = "0.11.0-beta.6"
baid58 = "0.4.4"
bp-std = "0.11.0-beta.6"
bp-core="0.11.0-beta.6"
rgb-std = "0.11.0-beta.6"
rgb-schemata = "0.11.0-beta.6"
strict_types = "1.6.4"
rgb-runtime = "0.11.0-beta.6"
strict_encoding = "~2.6.7"
rust-version = "1.79.0"
bitcoin = "0.1.1"
musig2 = "0.0.5"
bp-esplora = "0.11.0-beta.4"
automerge = "0.5.2"
autosurgeon = "0.8"
ascii-armor = "0.2.0"
bdk = "1.0.0-alpha.12"
bdk-cli = "0.27.1"
bdk-macros = "0.27.1"
bdk-wallet = "0.27.1"
bdk-wallet-cli = "0.27.1"

[rust_bitcoin]
[patch.crates-io.bitcoin]
path = "bitcoin"

[patch.crates-io.bitcoin_hashes]
path = "hashes"

[patch.crates-io.bitcoin-internals]
path = "internals"


default = ["bolt", "strict_encoding"]
all = ['bifrost', "serde"]
bolt = ["lightning_encoding", "strict_encoding"] # Remove strict encoding requirement
bifrost = ["strict_encoding", "bolt"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/serde"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"


