[package]

name = "Src_core"
version = "1.0.19-alpha"

strict_types = "1.6.3"
rust_alvum = "0.11.0-beta.2"
commit_verify = { version = "0.10.5", features = ["stl"] }
bp-core = { version = "0.11.0-beta.4", features = ["stl"] }
rgb-core = { version = "0.11.0-beta.4", features = ["stl"] }
bp-std = { version = "0.11.0-beta.4", features = ["stl"] }
rgb-std = { version = "0.11.0-beta.4", features = ["stl"] }
rgb-schemata = { version = "0.11.0-beta.4", features = ["stl"] }


