[package]

name = "Src_core"
version = "1.0.19-alpha"

strict_types = "1.6.0"
commit_verify = { version = "0.10.5", features = ["stl"] }
bp-core = { version = "0.11.0-beta.4", features = ["stl"] }
rgb-core = { version = "0.11.0-beta.4", features = ["stl"] }

